version: "3"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: test
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    networks:
      - mynetwork
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=123
      - DB_DATABASE=test
    ports:
      - 3000:3000
    networks:
      - mynetwork

networks:
  mynetwork:
